espnet: 0.9.2
files:
  asr_model_file: exp/asr_train_asr_transformer2_ddp_raw_bpe/valid.acc.ave_10best.pth
python: "3.7.7 (default, May  7 2020, 21:25:33) \n[GCC 7.3.0]"
timestamp: 1603015704.623382
torch: 1.5.0
yaml_files:
  asr_train_config: exp/asr_train_asr_transformer2_ddp_raw_bpe/config.yaml
